### DISCUSSION TITLE
ApexCharts Card and "Verlauf" do not show any historical data

### DISCUSSION THREAD

**Discussion by mike4001** [DarwinsBuddy/WienerNetzeSmartmeter#151] [Q&A] [answered]
Hi,

I have a weird issue. I did the integration and can see both normal "Zählpunkt" as well as the historical data in the standard statistics diagrams in Home Assistant. I can even show hourly data or the change from the last day .... so far so good.

```
chart_type: bar
period: hour
days_to_show: 1
type: statistics-graph
entities:
  - sensor.at00100000000000000010000xxxxxxxx_statistics
stat_types:
  - change
```

But my ApexCharts Card states that there is no data available.

```
type: custom:apexcharts-card
graph_span: 1d
span:
  start: day
  offset: '-1d'
series:
  - entity: sensor.at00100000000000000010000xxxxxxxx_statistics
```

I think that the problem lies there that also if I check the entity in "Verlauf" it also shows no data. But then again .... Standard Statistics Diagrams do work.

Has anyone an idea what could be wrong here?

Thanks
