### ISSUE TITLE
Late data - not from yesterday

### ISSUE THREAD

**Issue by lordmatthi** [DarwinsBuddy/WienerNetzeSmartmeter#303]
Dear all!

As I know "WienerNetzeSmartmeter" should provide data from yesterday. But I only see data from the day before. Example: If it is friday I can see it from wednesday and not from thursday. Is it possible to fix because online on wienernetze.at I can see it from yesterday.

Sensor will refresh at the moment between 5 and 6am. Maybe it would fix the issue if this "time window" is later or it is possible to configure it in the options. I am right, that this integration only requests the data 1 time a day or is it caused by the API?

Thanks!

**Comment by Macusercom** [comment]
I have the same issue still. I'm automatically fetching the data at 7 AM, I'll try to fetch it earlier but not sure if this offsets it into the right direction

**Comment by oliverbayer** [comment]
I have the issue, that values from yesterday are shown today, has anybody an idea how to fix it?

**Comment by reox** [comment]
You can use the statistics to get the daily statistics, for example:
```
type: statistic
period:
  calendar:
    period: day
    offset: -1
stat_type: change
entity: wnsm:at001009823789237589
name: Gestern
layout_options:
  grid_columns: 2
  grid_rows: 2
```

and `offset: -2` for the day before. The values match for me exactly.

The meter value itself is rather useless to get actual daily stats from :/
